on:
  push:
    branches:
      - development

      
name: Development ENV

jobs:
  release:
    name: Create Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: development
         


