name: Dev Pipeline

on:
  push:
    branches:
      - development

jobs:
  release:
    name: Create Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: development
      - name: Check
        run: | 
          ls
         


