on:
  workflow_dispatch:
      
name: Running the pipeline for development ENV

jobs:
  release:
    name: Create Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: development
      - name: Display
        run: |
          echo "Finished running development pipeline"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Repository: ${{ github.repository }}"

