name: UAT env

on:
  workflow_dispatch:
  push:
    branches:
      - 'uat'
      
permissions:
  id-token: write
  contents: read
  
jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          echo "test-1"
  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          echo "test-2"
          
  release-job:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'uat'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: DBK Release
          body: |
            Creating a releases file
      
  failure-event:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    if: always()  && (needs.test-1.result == 'failure' || needs.test-2.result == 'failure') 
    steps:
      - run: |
          echo "Sending mail"
