on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'uat'
      
name: uat ENV

jobs:
  intergration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          bjkhljlkj
    
  release-job:
    runs-on: ubuntu-latest
    needs: intergration-test
    steps:
      - name: Commands
        run: |
            echo "hi"
      
  d:
    runs-on: ubuntu-latest
    needs: [intergration-test]
    if: always() && contains(needs.*.result, 'failure')
    steps:
      - run: |
          echo "I don't want this to run unless b or c fails!"
          echo ${{ contains(needs.*.result, 'failure') }}   # Evaluates to false!
