on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'uat'
      
name: uat ENV

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          echo test1
  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
         echo test2
          
  release-job:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    steps:
      - name: Commands
        run: |
            echo "hi"
      
  d:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    if: always() && contains(needs.*.result, 'success')
    steps:
      - run: |
          echo "I don't want this to run unless b or c fails!"
          echo ${{ contains(needs.*.result, 'failure') }}   # Evaluates to false!
