on:
  push:
    branches:
      - 'main'
      
name: uat ENV

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        runss: |
          echo test1
  test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        runss: |
         echo test2
          
  release-job:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    steps:
      - name: Commands
        run: |
            echo "hi"
      
  d:
    runs-on: ubuntu-latest
    needs: [test-1,test-2]
    if: always()  && (needs.test-1.result == 'failure' || needs.test-2.result == 'failure') 
    steps:
      - run: |
          echo "I don't want this to run unless b or c fails!"
          echo ${{ contains(needs.*.result, 'failure') }}   # Evaluates to false!
