on:
  push:
    branches:
      - 'uat'
      
name: uat ENV

jobs:
  intergration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         ref: uat
      - name: Display
        run: |
          USER=${{ github.repository_owner }}
          REPO=${{ github.event.repository.name }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          API_URL="https://api.github.com/repos/${USER}/${REPO}/releases/latest"
          curl -s -H "Authorization: token ${TOKEN}" "${API_URL}"
    
  release-job:
    name: Create Releases
    runs-on: ubuntu-latest
    needs: intergration-test
    steps:
      - name: Commands
        with: |
            ls
