on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'uat'
      
name: uat ENV

jobs:
  intergration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Display
        run: |
          API_URL="https://api.github.com/repos/${USER}/${REPO}/releases/latest"
          curl -s -H "Authorization: token ${TOKEN}" "${API_URL}"
    
  release-job:
    runs-on: ubuntu-latest
    needs: intergration-test
    steps:
      - name: Commands
        run: |
            echo "hi"
